// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuyVUy7qBcOPrtAV4yfUBZDIFFQhCA1hM',
    appId: '1:130238802097:web:20fbc53e7d1a302ba7da90',
    messagingSenderId: '130238802097',
    projectId: 'wishi-f28f3',
    authDomain: 'wishi-f28f3.firebaseapp.com',
    databaseURL: 'https://wishi-f28f3-default-rtdb.firebaseio.com',
    storageBucket: 'wishi-f28f3.firebasestorage.app',
    measurementId: 'G-T5LN90TB41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GWzCiz67SLfPi9MDpxDNwQk_KNirAe0',
    appId: '1:130238802097:android:3e94f6664b8b16efa7da90',
    messagingSenderId: '130238802097',
    projectId: 'wishi-f28f3',
    databaseURL: 'https://wishi-f28f3-default-rtdb.firebaseio.com',
    storageBucket: 'wishi-f28f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMhv4UG-LZyY0H7TwIEzMQEi-IKs3FFq8',
    appId: '1:130238802097:ios:eb5b0f68cdc09db6a7da90',
    messagingSenderId: '130238802097',
    projectId: 'wishi-f28f3',
    databaseURL: 'https://wishi-f28f3-default-rtdb.firebaseio.com',
    storageBucket: 'wishi-f28f3.firebasestorage.app',
    iosClientId: '130238802097-8cjteccdvt07ufce7k4m8v5nkb1pprtn.apps.googleusercontent.com',
    iosBundleId: 'com.example.wishiApp',
  );
}
